info:
  title: my_project ффффф
  version: 0.1.0
openapi: 3.0.2
paths:
  /:
    get:
      operationId: index__get
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: Index
  /api/item/:
    get:
      operationId: item_api_item__get
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: Item
  /info/:
    get:
      operationId: info_info__get
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: Info
