version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: ./etc/docker/web/Dockerfile
      args:
        GID: ${GROUP_ID}
        UID: ${USER_ID}
    volumes:
      - .:/home/web
      - ./app/static:/var/www/static
      - ./var/volumes/media:/var/www/media
      - ./var/volumes/db:/var/db
    command: [
      # "echo", "1",
      "uvicorn", "app.main:app", "--host", "0.0.0.0", "--reload", "--reload-dir=app", "--reload-delay=1"
    ]
    environment:
      - FASTAPI_DOTENV=etc/env/dev
    # env_file:
    #   - etc/env/.dev

  # db:
  #   image: docker.io/mysql:debian
  #   command: --default-authentication-plugin=mysql_native_password
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: example

  nginx:
    build: ./etc/docker/nginx
    ports: ["8080:8080"]
    user: ${USER_ID}
    volumes:
      - ./app/static:/var/www/static
