[project]
name = "app"
version = "0.0.0"
dependencies = [
    "fastapi",
    "pydantic",
    "pydantic[dotenv]",
    "pyyaml",
    "sqlalchemy",
    "sqlalchemy[asyncio]",
    # "aiosqlite",
    # "asyncpg",
    "asyncmy", "mysqlclient", "cryptography",
    "uvicorn",
]

[project.optional-dependencies]
dev = [
    "alembic",
    "aiosqlite",
    "httpx",
    "pytest",
    "pytest-asyncio",
    "pytest-cov",
    "pytest-mypy",
    "pytest-pylint",
    "sqlalchemy[mypy]"
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.mypy]
exclude = "venv"
plugins = ["pydantic.mypy", "sqlalchemy.ext.mypy.plugin"]

[tool.setuptools]
packages = ["app"]

[tool.pytest.ini_options]
asyncio_mode = "auto"
disable_test_id_escaping_and_forfeit_all_rights_to_community_support = true
addopts = [
    "--pylint",
    "--mypy",
    "--cov=app", "--cov-report=xml", "--no-cov-on-fail",
    # "-k", "test_testname",
    # "-k", "test_item",
    "-r", "A",
    # "-vv",
    # "--showlocals",
]
testpaths = [
    "tests",
    "app",
]
filterwarnings = [
    "ignore::DeprecationWarning:pylint*",
    "ignore::DeprecationWarning:pytest_pylint*",
]
