"""init

Revision ID: 457907d0ffe9
Revises: 
Create Date: 2022-08-28 20:48:11.585795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '457907d0ffe9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item')
    # ### end Alembic commands ###
